version: "3"

services:
  fronend:
    build:
      context: .
      dockerfile: Dockerfile                     
    image: ${DOCKER_IMAGE_NAME:-hediaminv1frontimg}:${TAG:-latest}
    container_name: ${DOCKER_CONTAINER_NAME:-hediaminV1Container}
    ports:
      - ${APP_PORT:-3001}:3001    
    restart: unless-stopped

